Aufgabe 1
t-azubi/Programmieren pull request #1
Opened 2018-10-04 17:41 UTC by Zeroks77

Hey Paul, hast du einen Verbesserungsvorschlag ?
Das sollten wir in EBA machen wenn uns langweilig ist.

2018-10-09 07:10 UTC, paule96 requested changes

2018-10-09 07:10 UTC, paule96 commented on EBA/Snackautomat/Snacks/src/Snacks/Program.cs
> +    class Hunger
static class Hunger

2018-10-09 07:10 UTC, paule96 commented on EBA/Snackautomat/Snacks/src/Snacks/Program.cs
> +    class Hunger
wäre schön das auch in einem extra file zu haben

2018-10-09 07:10 UTC, paule96 commented on EBA/Snackautomat/Snacks/src/Snacks/Program.cs
> +            return -1;
das kommt bitte in das Default vom Switch case

2018-10-09 07:10 UTC, paule96 commented on EBA/Snackautomat/Snacks/src/Snacks/Program.cs
> +            return -1;
das kommt bitte in das Default vom Switch case

2018-10-09 07:10 UTC, paule96 commented on EBA/Snackautomat/Snacks/src/Snacks/Form1.cs
> +            return "Whatever you want";
das kommt bitte in das Default vom Switch case

2018-10-09 18:20 UTC, paule96 reviewed
Hast du das nochmal geschaut ob es baut? Wenn ja ist das für mich fein.

2018-10-10 06:43 UTC, Zeroks77 commented
@paule96  alles funktioniert :D 
hab auch eine Readme für den Ordner EBA geschrieben

2018-11-01 13:53 UTC, paule96 approved these changes

2018-11-02 15:35 UTC, merged