Update README.md
t-azubi/Programmieren pull request #8
Opened 2019-08-16 08:56 UTC by JanMichels

jetzt gehts

2019-08-16 08:58 UTC, Zeroks77 commented on README.md
> +Danke, dass du dir die Zeit genommen hast, mich zu lesen. Hab einen schönen Tag und viel Spaß beim Programmieren ihr Penner.
bitte etwas Freundlicher gestallten :)

2019-08-16 08:59 UTC, Zeroks77 requested changes
Nicht Ok

2019-08-16 09:04 UTC, Zeroks77 requested changes
Kannste vergessen

2019-08-16 09:09 UTC, Zeroks77 requested changes
Wäre Cool wenn du so ne scheiße lassen köntest 😪

2019-08-16 09:10 UTC, Zeroks77 commented on README.md
> +Danke, dass du dir die Zeit genommen hast, mich zu lesen. Hab einen schönen Tag und viel Spaß beim Programmieren ihr Mongos.
Immer noch echt nicht so, dass man das leuten vorlegen kann

2019-08-16 09:23 UTC, closed without merging

2019-08-19 09:48 UTC, paule96 commented
seit mal nett zu einander!